apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
data:
  APP_NAME: Industry Exports Directory
  APP_ENV: local
  Front_APP_URL: frontend.default.svc.cluster.local
  Back_APP_URL: admin.default.svc.cluster.local
  CLIENT_BASE_URL: apiserver.default.svc.cluster.local
  APP_DEBUG: "false"
  APP_URL: apiserver.default.svc.cluster.local
  LOG_CHANNEL: stack
  LOG_LEVEL: debug
  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_DATABASE: pos
  DB_USERNAME: nur
  BROADCAST_DRIVER: log
  CACHE_DRIVER: redis
  QUEUE_CONNECTION: sync
  SESSION_DRIVER: file
  SESSION_LIFETIME: "120"
  SESSION_SECURE_COOKIE: "false"
  PROMETHEUS_NAMESPACE: default
  PROMETHEUS_METRICS_ROUTE_ENABLED: "true"
  PROMETHEUS_METRICS_ROUTE_PATH: metrics
  PROMETHEUS_METRICS_ROUTE_MIDDLEWARE: "null"
  PROMETHEUS_STORAGE_ADAPTER: memory
  PROMETHEUS_REDIS_PREFIX: PROMETHEUS_