apiVersion: v1
kind: ConfigMap
metadata:
  name: test_config
data:
  Front_APP_URL: frontend.default.svc.cluster.local
  Back_APP_URL: admin.default.svc.cluster.local
  CLIENT_BASE_URL: apiserver.default.svc.cluster.local
  APP_URL: apiserver.default.svc.cluster.local
 