apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always 
      containers:
      - name: hotel
        image: tazamun/hotel:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8069
          protocol: TCP
        - containerPort: 8071
          protocol: TCP
        env:
        - name: HOST
          value: postgres.default.svc.cluster.local
        - name: USER
          value: odoo
        - name: PASSWORD
          value: odoo
        - name: DATABASE
          value: hotel
